# Staging environment configuration
# Configuration that mimics production but with staging-specific settings

spring:
  profiles:
    active: staging
  
  # Staging database configuration
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

  # Staging security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://staging-auth.mcp.zamaz.com/auth/realms/mcp}

# Logging - balanced for staging
logging:
  level:
    root: INFO
    com.zamaz.mcp: INFO
    org.springframework: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

# Management endpoints - limited exposure
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

# Server configuration for staging
server:
  error:
    include-stacktrace: on-param
    include-exception: false

# Staging CORS
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://staging.mcp.zamaz.com,https://staging-admin.mcp.zamaz.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Cache configuration for staging
spring.cache:
  type: redis
  redis:
    time-to-live: 600000 # 10 minutes
    cache-null-values: false

# Staging-specific feature flags
features:
  debug-mode: false
  swagger-enabled: true
  mock-external-services: false

# Staging JWT configuration (encrypted)
jwt:
  secret: '{cipher}${JWT_SECRET_ENCRYPTED}'
  expiration: 3600 # 1 hour
  refresh-expiration: 86400 # 24 hours

# Staging rate limiting
rate-limiting:
  enabled: true
  requests-per-minute: 100
  requests-per-hour: 5000

# Staging monitoring
monitoring:
  tracing:
    enabled: true
    sampling-rate: 0.1 # Sample 10% of requests

# Database connection pool for staging
datasource:
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    connection-timeout: 20000
    idle-timeout: 300000
    max-lifetime: 1200000

# Staging Redis configuration
redis:
  host: ${REDIS_HOST:staging-redis.mcp.zamaz.com}
  port: ${REDIS_PORT:6379}
  password: '{cipher}${REDIS_PASSWORD_ENCRYPTED}'
  timeout: 2000
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 2