# Production environment configuration
# Secure, optimized settings for production

spring:
  profiles:
    active: prod
  
  # Production database configuration
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

  # Production security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWT_JWK_SET_URI}

# Production logging - minimal
logging:
  level:
    root: WARN
    com.zamaz.mcp: INFO
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
  file:
    name: /var/log/mcp/${spring.application.name}.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 3GB

# Management endpoints - minimal exposure
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true
        pushgateway:
          enabled: true
          base-url: ${PROMETHEUS_PUSHGATEWAY_URL}

# Server configuration for production
server:
  error:
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: false
  compression:
    enabled: true
    min-response-size: 1024
  http2:
    enabled: true
  forward-headers-strategy: native

# Production CORS - restrictive
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: GET,POST,PUT,DELETE
  allowed-headers: Authorization,Content-Type,X-Requested-With
  allow-credentials: true
  max-age: 86400

# Production cache configuration
spring.cache:
  type: redis
  redis:
    time-to-live: 3600000 # 1 hour
    cache-null-values: false
    enable-statistics: true

# Production feature flags
features:
  debug-mode: false
  swagger-enabled: false
  mock-external-services: false

# Production JWT configuration (all encrypted)
jwt:
  secret: '{cipher}${JWT_SECRET_ENCRYPTED}'
  expiration: 1800 # 30 minutes
  refresh-expiration: 604800 # 7 days
  issuer: ${JWT_ISSUER}
  audience: ${JWT_AUDIENCE}

# Production rate limiting
rate-limiting:
  enabled: true
  requests-per-minute: 60
  requests-per-hour: 1000
  requests-per-day: 10000

# Production monitoring
monitoring:
  tracing:
    enabled: true
    sampling-rate: 0.01 # Sample 1% of requests
  metrics:
    enabled: true
    export-interval: 60s

# Production database connection pool
datasource:
  hikari:
    maximum-pool-size: 20
    minimum-idle: 10
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    leak-detection-threshold: 60000

# Production Redis configuration
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: '{cipher}${REDIS_PASSWORD_ENCRYPTED}'
  ssl: true
  timeout: 5000
  lettuce:
    pool:
      max-active: 16
      max-idle: 8
      min-idle: 4
    cluster:
      refresh:
        adaptive: true
        period: 60s

# Production message queue configuration
rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_USERNAME}
  password: '{cipher}${RABBITMQ_PASSWORD_ENCRYPTED}'
  virtual-host: ${RABBITMQ_VHOST:/}
  ssl:
    enabled: true

# Production async configuration
async:
  core-pool-size: 4
  max-pool-size: 16
  queue-capacity: 1000
  thread-name-prefix: mcp-async-

# Production security headers
security:
  headers:
    content-security-policy: "default-src 'self'"
    x-frame-options: DENY
    x-content-type-options: nosniff
    x-xss-protection: "1; mode=block"
    strict-transport-security: "max-age=31536000; includeSubDomains"