# Global default configuration for all MCP services
# These settings are inherited by all services unless overridden

spring:
  # Default Jackson configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: UTC

  # Default HTTP encoding
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # Default servlet configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Management endpoints (Actuator) configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:default}

# Logging configuration
logging:
  level:
    root: INFO
    com.zamaz.mcp: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/${spring.application.name}.log
    max-size: 10MB
    max-history: 30

# Server configuration defaults
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  error:
    include-message: always
    include-binding-errors: always
  shutdown: graceful

# Spring lifecycle configuration
spring.lifecycle.timeout-per-shutdown-phase: 30s

# Default resilience configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - java.net.ConnectException
          - java.io.IOException
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s

# Default API versioning
api:
  version: v1
  base-path: /api/${api.version}

# Default CORS configuration (to be overridden per environment)
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# Default cache configuration
spring.cache:
  type: caffeine
  caffeine:
    spec: maximumSize=500,expireAfterWrite=5m

# Thread pool configuration
task:
  execution:
    pool:
      core-size: 2
      max-size: 10
      queue-capacity: 500
      keep-alive: 60s
  scheduling:
    pool:
      size: 2