# Development configuration for mcp-organization
logging:
  level:
    com.zamaz.mcp: DEBUG
    org.springframework.web: DEBUG

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Development database
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mcp_organization_db}
    username: ${DB_USER:dev_user}
    password: ${DB_PASSWORD:{cipher}encrypted_dev_password}
