# MCP Organization Service - Production Configuration
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: '{cipher}${DB_PASSWORD_ENCRYPTED}'
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

# Production specific settings
organization:
  defaults:
    max-users-per-org: ${MAX_USERS_PER_ORG}
    max-debates-per-org: ${MAX_DEBATES_PER_ORG}
  
  features:
    debug-endpoints: false
    test-data-generation: false
    audit-logging: true

# Production Redis settings
spring.redis:
  password: '{cipher}${REDIS_PASSWORD_ENCRYPTED}'
  ssl: true
  lettuce:
    pool:
      max-active: 16
      max-idle: 8

# Minimal logging for production
logging:
  level:
    com.zamaz.mcp.organization: INFO
    org.springframework: WARN