# Staging configuration for mcp-context
logging:
  level:
    com.zamaz.mcp: INFO

# Staging database
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres-staging:5432/mcp_context_db}
    username: ${DB_USER:staging_user}
    password: ${DB_PASSWORD:{cipher}encrypted_staging_password}
