apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-integration-logs-pvc
  namespace: github-integration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard