apiVersion: v1
kind: Service
metadata:
  name: github-integration
  namespace: github-integration
  labels:
    app: github-integration
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: github-integration
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP