apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
  namespace: mcp-system
data:
  git.repo.uri: "https://github.com/zamaz/mcp-config-repo.git"
  git.branch: "main"
  application.yml: |
    server:
      port: 8888
    
    spring:
      application:
        name: mcp-config-server
      cloud:
        config:
          server:
            git:
              uri: ${CONFIG_GIT_REPO_URI}
              default-label: ${CONFIG_GIT_BRANCH:main}
              clone-on-start: true
              timeout: 10
              search-paths:
                - '{application}'
                - '{application}/{profile}'
                - 'shared'
              force-pull: true
            health:
              repositories:
                mcp:
                  label: main
                  profiles: default
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus,refresh,bus-refresh
      health:
        readinessState:
          enabled: true
        livenessState:
          enabled: true
      metrics:
        export:
          prometheus:
            enabled: true
    
    logging:
      level:
        org.springframework.cloud.config: INFO
        org.springframework.cloud.bus: INFO