apiVersion: v1
kind: Secret
metadata:
  name: config-server-secrets
  namespace: mcp-system
type: Opaque
stringData:
  encryption.key: "CHANGE_ME_IN_PRODUCTION"  # Base64 encoded encryption key
  server.username: "admin"
  server.password: "CHANGE_ME_IN_PRODUCTION"
  git.ssh.key: ""  # Base64 encoded SSH private key for Git access (optional)
---
apiVersion: v1
kind: Secret
metadata:
  name: config-server-ssh-keys
  namespace: mcp-system
type: Opaque
data:
  id_rsa: ""  # Base64 encoded SSH private key
  known_hosts: ""  # Base64 encoded known_hosts file