# Shared Database Configuration
# Common database settings used across all services

spring:
  datasource:
    hikari:
      # Connection pool settings
      connection-test-query: SELECT 1
      validation-timeout: ${DB_VALIDATION_TIMEOUT:5000}
      leak-detection-threshold: ${DB_LEAK_DETECTION_THRESHOLD:60000}
      
      # Pool sizing defaults
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:2}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      
      # Pool behavior
      auto-commit: ${DB_AUTO_COMMIT:true}
      connection-init-sql: ${DB_INIT_SQL:}
      
  jpa:
    # Common JPA settings
    properties:
      hibernate:
        # Performance settings
        jdbc:
          batch_size: ${HIBERNATE_BATCH_SIZE:25}
          batch_versioned_data: true
          fetch_size: ${HIBERNATE_FETCH_SIZE:100}
          
        # Second level cache
        cache:
          use_second_level_cache: ${L2_CACHE_ENABLED:true}
          use_query_cache: ${QUERY_CACHE_ENABLED:true}
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
            
        # Statistics
        generate_statistics: ${HIBERNATE_STATISTICS:false}
        
        # SQL formatting (non-production)
        format_sql: ${HIBERNATE_FORMAT_SQL:false}
        use_sql_comments: ${HIBERNATE_SQL_COMMENTS:false}
        
    # Open Session in View - should be false for production
    open-in-view: ${JPA_OPEN_IN_VIEW:false}
    
    # Hibernate DDL auto
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

# Database migration settings (Flyway)
spring.flyway:
  enabled: ${FLYWAY_ENABLED:true}
  baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
  validate-on-migrate: ${FLYWAY_VALIDATE_ON_MIGRATE:true}
  clean-disabled: ${FLYWAY_CLEAN_DISABLED:true}
  locations: classpath:db/migration
  sql-migration-prefix: V
  sql-migration-suffixes: .sql
  placeholder-replacement: true
  placeholders:
    schema_name: ${DB_SCHEMA:public}