# GitLeaks configuration file

title = "GitLeaks Configuration"

# Global settings
[allowlist]
description = "Global allowlist"
paths = [
    '''.*\.md$''',
    '''(.*?)(jpg|jpeg|png|gif|bmp|svg)$''',
    '''(.*?)(woff|woff2|eot|ttf|otf)$''',
    '''(.*?)(mp4|webm|ogg)$''',
    '''(.*?)(mp3|wav|flac)$''',
    '''(.*?)(zip|tar|gz|rar)$''',
    '''(.*?)(pdf|doc|docx|xls|xlsx|ppt|pptx)$''',
    '''(.*?)(lock|lockb)$''',
    '''(.*?)\.min\.(js|css)$''',
    '''(.*?)\.test\.(js|ts|java)$''',
    '''(.*?)\.example$''',
    '''(.*?)\.sample$''',
    '''(.*?)\.template$''',
]

regexes = [
    '''example.*''',
    '''sample.*''',
    '''test.*''',
    '''mock.*''',
    '''dummy.*''',
]

# Rules
[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
tags = ["aws", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
tags = ["aws", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "aws-mws-key"
description = "AWS MWS Key"
regex = '''amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'''
tags = ["aws", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["github", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "github-oauth"
description = "GitHub OAuth Access Token"
regex = '''gho_[0-9a-zA-Z]{36}'''
tags = ["github", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "github-app-token"
description = "GitHub App Token"
regex = '''(ghu|ghs)_[0-9a-zA-Z]{36}'''
tags = ["github", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "github-refresh-token"
description = "GitHub Refresh Token"
regex = '''ghr_[0-9a-zA-Z]{76}'''
tags = ["github", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "slack-token"
description = "Slack Token"
regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})'''
tags = ["slack", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "slack-webhook"
description = "Slack Webhook"
regex = '''https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}'''
tags = ["slack", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
tags = ["key", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*'''
tags = ["jwt", "credentials"]
severity = "HIGH"

[[rules]]
id = "password-in-code"
description = "Password in Code"
regex = '''(?i)(password|passwd|pwd|secret|token)(.{0,20})?[=:>][^,);\n]{0,30}['"][^'"]{4,}['"]'''
tags = ["password", "credentials"]
severity = "HIGH"
[rules.allowlist]
regexes = [
    '''(?i)(password|passwd|pwd|secret|token)(.{0,20})?[=:>][^,);\n]{0,30}['"](\$\{[^}]+\}|[a-zA-Z_][a-zA-Z0-9_]*\.[a-zA-Z_][a-zA-Z0-9_]*|[a-zA-Z_][a-zA-Z0-9_]*\[[^\]]+\]|[a-zA-Z_][a-zA-Z0-9_]*\([^)]*\))['"]''',
    '''(?i)(password|passwd|pwd|secret|token)(.{0,20})?[=:>][^,);\n]{0,30}['"](\{\{[^}]+\}\}|<%=.*%>|<\?.*\?>)['"]''',
    '''(?i)(password|passwd|pwd|secret|token)(.{0,20})?[=:>][^,);\n]{0,30}['"][a-zA-Z_][a-zA-Z0-9_]*['"]''',
]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)['"]?api[_-]?key['"]?[^,);\n]{0,30}['"][0-9a-zA-Z]{16,45}['"]'''
tags = ["api", "credentials"]
severity = "HIGH"

[[rules]]
id = "generic-secret"
description = "Generic Secret"
regex = '''(?i)['"]?secret['"]?[^,);\n]{0,30}['"][0-9a-zA-Z]{16,45}['"]'''
tags = ["secret", "credentials"]
severity = "HIGH"

[[rules]]
id = "basic-auth"
description = "Basic Authentication"
regex = '''(?i)basic [a-zA-Z0-9+/]+={0,2}'''
tags = ["auth", "credentials"]
severity = "HIGH"

[[rules]]
id = "authorization-bearer"
description = "Authorization Bearer Token"
regex = '''(?i)bearer [a-zA-Z0-9\._\-]+'''
tags = ["auth", "credentials"]
severity = "MEDIUM"

[[rules]]
id = "mailchimp-api-key"
description = "Mailchimp API Key"
regex = '''(?i)[0-9a-f]{32}-us[0-9]{1,2}'''
tags = ["mailchimp", "credentials"]
severity = "HIGH"

[[rules]]
id = "stripe-api-key"
description = "Stripe API Key"
regex = '''(?i)sk_live_[0-9a-zA-Z]{24}'''
tags = ["stripe", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "stripe-restricted-api-key"
description = "Stripe Restricted API Key"
regex = '''(?i)rk_live_[0-9a-zA-Z]{24}'''
tags = ["stripe", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "google-api-key"
description = "Google API Key"
regex = '''AIza[0-9A-Za-z\\-_]{35}'''
tags = ["google", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "google-oauth-id"
description = "Google OAuth ID"
regex = '''[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com'''
tags = ["google", "credentials"]
severity = "HIGH"

[[rules]]
id = "google-oauth-secret"
description = "Google OAuth Secret"
regex = '''[0-9A-Za-z\\-_]{24}'''
tags = ["google", "credentials"]
severity = "HIGH"

[[rules]]
id = "firebase-key"
description = "Firebase Key"
regex = '''AAAA[A-Za-z0-9_-]{7}:[A-Za-z0-9_-]{140}'''
tags = ["firebase", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "twilio-api-key"
description = "Twilio API Key"
regex = '''SK[0-9a-fA-F]{32}'''
tags = ["twilio", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "twilio-account-sid"
description = "Twilio Account SID"
regex = '''AC[a-zA-Z0-9]{32}'''
tags = ["twilio", "credentials"]
severity = "HIGH"

[[rules]]
id = "twilio-auth-token"
description = "Twilio Auth Token"
regex = '''(?i)twilio(.{0,20})?['\"][0-9a-f]{32}['\"]'''
tags = ["twilio", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "sendgrid-api-key"
description = "SendGrid API Key"
regex = '''SG\.[0-9A-Za-z\-_]{22}\.[0-9A-Za-z\-_]{43}'''
tags = ["sendgrid", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "npm-access-token"
description = "NPM Access Token"
regex = '''npm_[0-9a-zA-Z]{36}'''
tags = ["npm", "credentials"]
severity = "CRITICAL"

[[rules]]
id = "environment-variable"
description = "Environment Variable"
regex = '''(?i)(ENVIRONMENT|ENV|APP_ENV|NODE_ENV|RAILS_ENV|RACK_ENV|DJANGO_ENV|FLASK_ENV)(.{0,20})?[=:>][^,);\n]{0,30}['"](?!prod|production|stage|staging|test|development|dev|local|localhost)[a-zA-Z0-9_-]+['"]'''
tags = ["env", "configuration"]
severity = "MEDIUM"