server:
  port: 5004
  servlet:
    context-path: /

spring:
  application:
    name: mcp-rag
  
  datasource:
    url: jdbc:postgresql://postgres:5432/rag_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  data:
    redis:
      host: redis
      port: 6379
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# MCP Configuration
mcp:
  service:
    name: mcp-rag
    version: 1.0.0
    description: "Retrieval Augmented Generation service for MCP"
  
  vector:
    type: in-memory  # For now, using in-memory storage
    dimension: 1536
    
# Logging
logging:
  level:
    com.zamaz.mcp.rag: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"