spring:
  application:
    name: mcp-rag
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rag_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:?Database password must be provided}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: RagHikariPool
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    open-in-view: false
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000
    connect-timeout: 2000
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: ${SERVER_PORT:5004}
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.zamaz.mcp: ${LOG_LEVEL:INFO}
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

mcp:
  cache:
    enabled: true
    default-ttl: PT30M
    redis:
      enabled: true
      max-memory-policy: allkeys-lru
      key-prefixes:
        rag: rag:
  
  async:
    redis-streams:
      enabled: true
      stream-names:
        rag-document-ingestion: rag:document:ingestion
      consumer-group-names:
        rag-document-ingestion: rag-document-ingestion-group
      consumer-names:
        rag-document-ingestion: rag-document-ingestion-consumer
      polling:
        poll-timeout: PT0.1S
  
  rag:
    qdrant-url: ${QDRANT_URL:http://qdrant:6333}
    
    embedding:
      default-model: text-embedding-3-large
      dimension: 1536
      batch-size: 100
    
    chunking:
      default-chunk-size: 1000
      default-chunk-overlap: 200
    
    retrieval:
      default-top-k: 5
      default-similarity-threshold: 0.7
    
    augmentation:
      max-tokens-per-source: 1000
      include-metadata: true
      include-sources: true
