spring:
  application:
    name: mcp-controller
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:debate_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: ControllerHikariPool
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    open-in-view: false
  
  # Redis configuration imported from common module
  config:
    import:
      - "classpath:application-redis.yml"
  
  profiles:
    include:
      - redis-high-throughput
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${MCP_CONTROLLER_PORT:${SERVER_PORT:5013}}
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.zamaz.mcp: ${LOG_LEVEL:INFO}
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

mcp:
  cache:
    enabled: true
    default-ttl: PT30M
    redis:
      enabled: true
      max-memory-policy: allkeys-lru
      key-prefixes:
        debate: dbt:
  
  controller:
    organization-service-url: ${ORGANIZATION_SERVICE_URL:http://mcp-organization:5005}
    llm-service-url: ${LLM_SERVICE_URL:http://mcp-llm:5002}
    
    # Hexagonal Architecture Configuration
    hexagonal:
      domain:
        event-publishing: ${DOMAIN_EVENT_PUBLISHING:true}
        validation-strict: ${DOMAIN_VALIDATION_STRICT:true}
      
      application:
        transaction-timeout: ${APP_TRANSACTION_TIMEOUT:30}
        retry-attempts: ${APP_RETRY_ATTEMPTS:3}
        use-case-logging: ${USE_CASE_LOGGING:true}
      
      adapters:
        web:
          validation-enabled: ${WEB_VALIDATION:true}
          swagger-enabled: ${SWAGGER_ENABLED:true}
          cors-enabled: ${CORS_ENABLED:true}
        
        persistence:
          optimistic-locking: ${OPTIMISTIC_LOCKING:true}
          batch-processing: ${BATCH_PROCESSING:true}
          audit-enabled: ${AUDIT_ENABLED:true}
    
    debate:
      # Enhanced debate configuration with hexagonal architecture support
      max-concurrent-debates: ${MAX_CONCURRENT_DEBATES:100}
      default-response-timeout: ${DEFAULT_RESPONSE_TIMEOUT:300}
      cleanup-completed-debates: ${CLEANUP_COMPLETED_DEBATES:true}
      cleanup-after-days: ${CLEANUP_AFTER_DAYS:30}
      
      formats:
        standard:
          max-rounds: 10
          turn-timeout-seconds: 300
          rules:
            - "participants_alternate"
            - "no_consecutive_turns"
        oxford:
          max-rounds: 6
          turn-timeout-seconds: 600
          rules:
            - "proposition_first"
            - "opposition_second"
            - "alternating_rebuttals"
        freestyle:
          max-rounds: 20
          turn-timeout-seconds: 180
          rules:
            - "free_participation"
        quick:
          max-rounds: 3
          turn-timeout-seconds: 120
          rules:
            - "fast_paced"
            - "auto_advance"
        ai_only:
          max-rounds: 8
          turn-timeout-seconds: 60
          rules:
            - "ai_participants_only"
            - "auto_advance"
      
      default-format: "standard"
      
      quality-assessment:
        enabled: ${QUALITY_ASSESSMENT_ENABLED:true}
        real-time: ${REAL_TIME_QUALITY:false}
        provider: ${QUALITY_PROVIDER:internal}
      
      summarization:
        default-strategy: "key_points"
        strategies:
          - "key_points"
          - "pro_con"
          - "chronological"
          - "thematic"
    
    websocket:
      enabled: ${WEBSOCKET_ENABLED:true}
      max-sessions: ${MAX_WEBSOCKET_SESSIONS:1000}
      heartbeat-interval: ${WEBSOCKET_HEARTBEAT:30}
    
    security:
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:${UI_PORT:3001},http://localhost:${MCP_GATEWAY_PORT:8080}}
        allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
        allowed-headers: ${CORS_ALLOWED_HEADERS:*}
        allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
      
      api-key:
        header-name: ${API_KEY_HEADER:X-API-Key}
        required: ${API_KEY_REQUIRED:false}
    
    external:
      llm-service:
        url: ${LLM_SERVICE_URL:http://mcp-llm:5002}
        timeout: ${LLM_SERVICE_TIMEOUT:30000}
        retry-attempts: ${LLM_SERVICE_RETRIES:3}
      
      context-service:
        url: ${CONTEXT_SERVICE_URL:http://mcp-context:5001}
        timeout: ${CONTEXT_SERVICE_TIMEOUT:10000}
        retry-attempts: ${CONTEXT_SERVICE_RETRIES:2}

# OpenAPI/Swagger Configuration for Hexagonal Architecture
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: MCP Debate Controller API
    description: Hexagonal Architecture API for managing debates, participants, and responses
    version: 2.0.0
    contact:
      name: MCP Team
      email: support@zamaz.com
