spring:
  application:
    name: mcp-controller
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:debate_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: ControllerHikariPool
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    open-in-view: false
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 2000
    connect-timeout: 2000
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:5013}
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.zamaz.mcp: ${LOG_LEVEL:INFO}
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

mcp:
  cache:
    enabled: true
    default-ttl: PT30M
    redis:
      enabled: true
      max-memory-policy: allkeys-lru
      key-prefixes:
        debate: dbt:
  
  controller:
    organization-service-url: ${ORGANIZATION_SERVICE_URL:http://mcp-organization:5005}
    llm-service-url: ${LLM_SERVICE_URL:http://mcp-llm:5002}
    
    debate:
      formats:
        standard:
          max-rounds: 10
          turn-timeout-seconds: 300
          rules:
            - "participants_alternate"
            - "no_consecutive_turns"
        oxford:
          max-rounds: 6
          turn-timeout-seconds: 600
          rules:
            - "proposition_first"
            - "opposition_second"
            - "alternating_rebuttals"
        freestyle:
          max-rounds: 20
          turn-timeout-seconds: 180
          rules:
            - "free_participation"
      
      default-format: "standard"
      
      summarization:
        default-strategy: "key_points"
        strategies:
          - "key_points"
          - "pro_con"
          - "chronological"
          - "thematic"
