spring:
  application:
    name: mcp-controller
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:debate_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:5013}
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

services:
  organization:
    url: ${ORGANIZATION_SERVICE_URL:http://localhost:5005}
  llm:
    url: ${LLM_SERVICE_URL:http://localhost:5002}

debate:
  defaults:
    max-rounds: 3
    max-response-length: 1000
    response-timeout: 5m
    allowed-formats:
      - OXFORD
      - LINCOLN_DOUGLAS
      - POLICY
      - PARLIAMENTARY
      - PUBLIC_FORUM

springdoc:
  api-docs:
    path: ${API_DOCS_PATH:/api-docs}
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    root: INFO
    com.zamaz.mcp.controller: DEBUG
    org.springframework.statemachine: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"