apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: zamaz-mcp
  labels:
    app: mcp-sidecar
type: Opaque
data:
  # Base64 encoded JWT secret key
  # This should be generated and stored securely in production
  # Example: echo -n 'your-secret-key-here' | base64
  secret: bWNwLXNpZGVjYXItc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: zamaz-mcp
  labels:
    app: mcp-sidecar
type: Opaque
data:
  # Base64 encoded Redis password
  # This should be generated and stored securely in production
  # Example: echo -n 'your-redis-password' | base64
  password: cmVkaXMtcGFzc3dvcmQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-config
  namespace: zamaz-mcp
  labels:
    app: mcp-sidecar
data:
  application.yml: |
    # Production configuration for MCP Sidecar
    server:
      port: 8080
      shutdown: graceful
    
    spring:
      application:
        name: mcp-sidecar
      profiles:
        active: production
      
      redis:
        host: redis-service
        port: 6379
        password: ${REDIS_PASSWORD}
        timeout: 2000ms
        jedis:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
            max-wait: 1000ms
    
    jwt:
      secret: ${JWT_SECRET}
      issuer: zamaz-mcp-sidecar
      expiration: 86400
      refresh-expiration: 604800
    
    # Rate limiting configuration
    rate-limit:
      redis-rate-limiter:
        replenish-rate: 10
        burst-capacity: 20
        requested-tokens: 1
    
    # Circuit breaker configuration
    resilience4j:
      circuitbreaker:
        configs:
          default:
            sliding-window-size: 10
            minimum-number-of-calls: 5
            failure-rate-threshold: 50
            wait-duration-in-open-state: 30s
            permitted-number-of-calls-in-half-open-state: 3
            automatic-transition-from-open-to-half-open-enabled: true
        instances:
          organization-service:
            base-config: default
          llm-service:
            base-config: default
            failure-rate-threshold: 60
            wait-duration-in-open-state: 60s
          debate-controller:
            base-config: default
          rag-service:
            base-config: default
    
    # Logging configuration
    logging:
      level:
        com.zamaz.mcp.sidecar: INFO
        org.springframework.security: WARN
        org.springframework.cloud.gateway: WARN
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
    
    # Actuator configuration
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: never
          show-components: never
      metrics:
        export:
          prometheus:
            enabled: true
        tags:
          application: ${spring.application.name}
          environment: production
    
    # CORS configuration
    app:
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:https://app.zamaz.com}
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-headers: "*"
        allow-credentials: true
        max-age: 3600
      
      # AI service configuration
      ai:
        services:
          gpt-4:
            url: http://mcp-llm-service:5002
            model: gpt-4
            priority: 1
            timeout: 30s
          claude:
            url: http://mcp-llm-service:5002
            model: claude-3
            priority: 2
            timeout: 30s
          local:
            url: http://mcp-llm-service:5002
            model: local-model
            priority: 3
            timeout: 15s
        
        load-balancer:
          strategy: round-robin
          health-check:
            interval: 30s
            timeout: 5s
            unhealthy-threshold: 3
            healthy-threshold: 2

---
apiVersion: v1
kind: Secret
metadata:
  name: sidecar-env-secrets
  namespace: zamaz-mcp
  labels:
    app: mcp-sidecar
type: Opaque
stringData:
  # Environment-specific secrets
  JWT_SECRET: "change-this-secret-in-production-environment"
  REDIS_PASSWORD: "secure-redis-password"
  
  # AI Service API Keys (if needed)
  OPENAI_API_KEY: "your-openai-api-key"
  ANTHROPIC_API_KEY: "your-anthropic-api-key"
  
  # Database credentials (if needed)
  DATABASE_PASSWORD: "secure-database-password"
  
  # External service credentials
  EXTERNAL_SERVICE_API_KEY: "external-service-api-key"