global:
  resolve_timeout: 5m
  smtp_from: 'alertmanager@mcp.example.com'
  smtp_smarthost: 'localhost:25'
  smtp_require_tls: false

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  
  routes:
    # Critical alerts
    - match:
        severity: critical
      receiver: 'critical'
      continue: true
    
    # Service-specific routing
    - match:
        service: gateway
      receiver: 'gateway-team'
    
    - match:
        service: llm
      receiver: 'ai-team'

# Receivers
receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://mcp-notification-service:5050/webhook/alerts'
        send_resolved: true

  - name: 'critical'
    webhook_configs:
      - url: 'http://mcp-notification-service:5050/webhook/critical'
        send_resolved: true
    # Uncomment for email notifications
    # email_configs:
    #   - to: 'oncall@example.com'
    #     headers:
    #       Subject: 'Critical Alert: {{ .GroupLabels.alertname }}'

  - name: 'gateway-team'
    webhook_configs:
      - url: 'http://mcp-notification-service:5050/webhook/gateway'
        send_resolved: true

  - name: 'ai-team'
    webhook_configs:
      - url: 'http://mcp-notification-service:5050/webhook/ai'
        send_resolved: true

# Inhibit rules
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']