apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-service
  namespace: workflow-editor
  labels:
    app: workflow-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workflow-service
      version: v1
  template:
    metadata:
      labels:
        app: workflow-service
        version: v1
    spec:
      containers:
      - name: workflow-service
        image: workflow-service:latest
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: metrics
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: NEO4J_URI
          valueFrom:
            configMapKeyRef:
              name: workflow-config
              key: neo4j.uri
        - name: NEO4J_USER
          valueFrom:
            secretKeyRef:
              name: workflow-secrets
              key: neo4j.user
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workflow-secrets
              key: neo4j.password
        - name: INFLUXDB_URL
          valueFrom:
            configMapKeyRef:
              name: workflow-config
              key: influxdb.url
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: workflow-secrets
              key: influxdb.token
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: workflow-config
              key: postgres.url
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: workflow-secrets
              key: postgres.user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workflow-secrets
              key: postgres.password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: workflow-service
  namespace: workflow-editor
  labels:
    app: workflow-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8081
    targetPort: 8081
    name: metrics
  selector:
    app: workflow-service