spring:
  application:
    name: mcp-modulith
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mcp_modulith}
    username: ${DB_USER:mcp_user}
    password: ${DB_PASSWORD:#{null}}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  modulith:
    events:
      # Enable event publication registry for guaranteed delivery
      publication-registry:
        enabled: true
    
    # Enable observability features
    observability:
      enabled: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.zamaz.mcp.modulith: DEBUG
    org.springframework.modulith: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Application-specific configuration
mcp:
  organization:
    default-tier: FREE
    max-free-debates: 10
  
  debate:
    default-max-rounds: 5
    default-max-turn-length: 500
    turn-timeout-seconds: 30
  
  llm:
    default-provider: openai
    providers:
      openai:
        enabled: true
        api-key: ${OPENAI_API_KEY:demo-key}
      claude:
        enabled: true
        api-key: ${CLAUDE_API_KEY:demo-key}
      gemini:
        enabled: true
        api-key: ${GEMINI_API_KEY:demo-key}