server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: kiro

scrape_configs:
  # Scrape Java service logs
  - job_name: java_services
    static_configs:
      - targets:
          - localhost
        labels:
          job: java_services
          __path__: /var/log/services/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger_name
            message: message
            correlation_id: correlation_id
            service: service_name
      - labels:
          level:
          service:
          correlation_id:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  # Scrape container logs
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
        filters:
          - name: label
            values: ["com.docker.compose.project=zamaz-debate-mcp"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            msg: msg
            correlation_id: correlation_id
      - labels:
          level:
          service:
      - timestamp:
          source: timestamp
          format: RFC3339
          fallback_formats:
            - UnixMs

  # Scrape Python service logs
  - job_name: python_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: python_services
          __path__: /var/log/python/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) - (?P<logger>\S+) - (?P<level>\w+) - (?P<message>.*)'
      - labels:
          level:
          logger:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'