version: '3.8'

services:
  # K6 Performance Test Runner
  k6:
    image: grafana/k6:latest
    container_name: mcp-k6-runner
    environment:
      - BASE_URL=http://gateway:8080
      - JWT_TOKEN=${JWT_TOKEN:-test-token}
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6:/scripts
      - ./results:/results
    command: run /scripts/debate-api-load-test.js
    networks:
      - mcp-network
    depends_on:
      - influxdb
      - grafana

  # Gatling Performance Test Runner
  gatling:
    build:
      context: ./gatling
      dockerfile: Dockerfile
    container_name: mcp-gatling-runner
    environment:
      - BASE_URL=http://gateway:8080
      - JWT_TOKEN=${JWT_TOKEN:-test-token}
    volumes:
      - ./gatling/results:/opt/gatling/results
      - ./gatling/src:/opt/gatling/user-files
    command: ["-s", "com.zamaz.mcp.performance.DebateAPILoadTest"]
    networks:
      - mcp-network

  # InfluxDB for storing performance metrics
  influxdb:
    image: influxdb:1.8
    container_name: mcp-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - mcp-network

  # Grafana for visualizing performance metrics
  grafana-perf:
    image: grafana/grafana:latest
    container_name: mcp-grafana-perf
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_AUTH_DISABLE_LOGIN_FORM=false
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - grafana-perf-data:/var/lib/grafana
    networks:
      - mcp-network
    depends_on:
      - influxdb

  # Locust for distributed load testing
  locust-master:
    image: locustio/locust
    container_name: mcp-locust-master
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master
    environment:
      - BASE_URL=http://gateway:8080
      - JWT_TOKEN=${JWT_TOKEN:-test-token}
    networks:
      - mcp-network

  locust-worker:
    image: locustio/locust
    container_name: mcp-locust-worker
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
    environment:
      - BASE_URL=http://gateway:8080
      - JWT_TOKEN=${JWT_TOKEN:-test-token}
    networks:
      - mcp-network
    depends_on:
      - locust-master
    deploy:
      replicas: 3

  # Artillery for quick performance tests
  artillery:
    image: artilleryio/artillery:latest
    container_name: mcp-artillery
    volumes:
      - ./artillery:/scripts
      - ./results:/results
    environment:
      - BASE_URL=http://gateway:8080
      - JWT_TOKEN=${JWT_TOKEN:-test-token}
    command: run /scripts/debate-api-test.yml
    networks:
      - mcp-network

volumes:
  influxdb-data:
  grafana-perf-data:

networks:
  mcp-network:
    external: true