groups:
  - name: service_health
    interval: 30s
    rules:
      # Service availability
      - alert: ServiceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
          service: '{{ $labels.job }}'
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 2 minutes"

      # High error rate
      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) by (job)
            /
            sum(rate(http_server_requests_seconds_count[5m])) by (job)
          ) > 0.05
        for: 5m
        labels:
          severity: high
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "Error rate is above 5% for the last 5 minutes"

      # High response time
      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95,
            sum(rate(http_server_requests_seconds_bucket[5m])) by (job, le)
          ) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time on {{ $labels.job }}"
          description: "95th percentile response time is above 1s"

  - name: resource_usage
    interval: 30s
    rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: |
          100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% for 10 minutes"

      # High memory usage
      - alert: HighMemoryUsage
        expr: |
          (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 85% for 10 minutes"

      # Database connection pool exhaustion
      - alert: DatabaseConnectionPoolExhausted
        expr: |
          hikaricp_connections_active / hikaricp_connections_max > 0.9
        for: 5m
        labels:
          severity: high
        annotations:
          summary: "Database connection pool near exhaustion"
          description: "Connection pool is over 90% utilized"

  - name: business_metrics
    interval: 1m
    rules:
      # Debate creation spike
      - alert: DebateCreationSpike
        expr: |
          rate(debates_created_total[5m]) > 10
        for: 5m
        labels:
          severity: info
        annotations:
          summary: "High debate creation rate"
          description: "More than 10 debates per minute created"

      # AI response time degradation
      - alert: AIResponseTimeDegradation
        expr: |
          histogram_quantile(0.95,
            sum(rate(ai_response_duration_seconds_bucket[5m])) by (provider, le)
          ) > 5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "AI response time degradation for {{ $labels.provider }}"
          description: "95th percentile AI response time is above 5s"

      # Cache hit rate low
      - alert: LowCacheHitRate
        expr: |
          (
            sum(rate(cache_hits_total[5m]))
            /
            (sum(rate(cache_hits_total[5m])) + sum(rate(cache_misses_total[5m])))
          ) < 0.5
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is below 50% for 15 minutes"

  - name: security_alerts
    interval: 30s
    rules:
      # Authentication failures
      - alert: HighAuthenticationFailures
        expr: |
          sum(rate(authentication_failures_total[5m])) > 10
        for: 5m
        labels:
          severity: high
        annotations:
          summary: "High authentication failure rate"
          description: "More than 10 authentication failures per minute"

      # Rate limit violations
      - alert: RateLimitViolations
        expr: |
          sum(rate(rate_violations_total[5m])) by (key) > 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High rate limit violations for {{ $labels.key }}"
          description: "More than 20 rate limit violations per minute"