global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mcp-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot services with actuator endpoints
  - job_name: 'debate-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['debate-engine:5013']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'debate-engine'

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'gateway'

  - job_name: 'organization'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['organization:5005']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'organization'

  - job_name: 'llm-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['llm:5002']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'llm-service'

  - job_name: 'rag-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rag:5004']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'rag-service'

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Node exporter for host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']