global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'mcp-production'
    env: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules files
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Postgres exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # MCP Gateway
  - job_name: 'mcp-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mcp-gateway:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'gateway'

  # MCP Organization Service
  - job_name: 'mcp-organization'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mcp-organization:5005']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'organization'

  # MCP Context Service
  - job_name: 'mcp-context'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mcp-context:5001']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'context'

  # MCP LLM Service
  - job_name: 'mcp-llm'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mcp-llm:5002']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'llm'

  # MCP Controller Service
  - job_name: 'mcp-controller'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mcp-controller:5013']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'controller'

  # MCP RAG Service
  - job_name: 'mcp-rag'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mcp-rag:5004']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'rag'

  # MCP Template Service
  - job_name: 'mcp-template'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mcp-template:5006']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'template'