{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mcp-config-server.fullname" . }}
  labels:
    {{- include "mcp-config-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mcp-config-server.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.serviceMonitor.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: 10s
{{- end }}