---
# YAML Linting Configuration
# This configuration is used by yamllint to check YAML files
# Documentation: https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Comments
  comments:
    min-spaces-from-content: 1
    require-starting-space: true

  # Document formatting
  document-start:
    present: false
    
  document-end:
    present: false

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Trailing spaces
  trailing-spaces: enable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  .github/workflows/*.yml
  docker-compose*.yml
  k8s/*.yaml
  k8s/**/*.yaml
  */target/*
  */build/*
  */node_modules/*
  .vscode/*
  .idea/*