global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'kiro-github-integration'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules files
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Webhook handler metrics
  - job_name: 'webhook-handler'
    static_configs:
      - targets: ['webhook-handler:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'webhook-handler'

  # PR processor metrics
  - job_name: 'pr-processor'
    static_configs:
      - targets: ['pr-processor:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'pr-processor'

  # Notification service metrics
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'notification-service'

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis'

  # Node exporter (if deployed)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Kubernetes service discovery for pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      # Only scrape pods with prometheus.io/scrape annotation
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      # Get metrics path from annotation
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      # Get port from annotation
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      # Add pod labels
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      # Add namespace
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      # Add pod name
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name