name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]


permissions:
  actions: read
  contents: read
  packages: write
  security-events: write
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_VERSION: '18'
  JAVA_VERSION: '17'

jobs:
  # Security and Code Quality
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          languages: java, javascript

  # Java Services Build and Test
  java-services:
    name: Java Services CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [mcp-common, mcp-security, mcp-gateway, mcp-controller, mcp-organization, mcp-testing]
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Compile ${{ matrix.service }}
        run: |
          if [ -d "${{ matrix.service }}" ]; then
            cd ${{ matrix.service }}
            mvn clean compile -B
          fi

      - name: Run unit tests
        run: |
          if [ -d "${{ matrix.service }}" ]; then
            cd ${{ matrix.service }}
            mvn test -B
          fi

      - name: Run integration tests
        run: |
          if [ -d "${{ matrix.service }}" ]; then
            cd ${{ matrix.service }}
            mvn verify -P integration-test -B
          fi

      - name: Generate test report
        uses: ./.github/actions/test-reporter
        if: success() || failure()
        with:
          name: Maven Tests (${{ matrix.service }})
          test-results: ${{ matrix.service }}/target/surefire-reports/*.xml
          reporter: junit
          create-issue-on-failure: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
          assignees: backend-team

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ${{ matrix.service }}/target/site/jacoco/jacoco.xml
          flags: ${{ matrix.service }}
          name: codecov-${{ matrix.service }}

  # Frontend Build and Test
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./debate-ui
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: debate-ui/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run type-check

      - name: Run unit tests
        run: npm run test:coverage

      - name: Build application
        run: npm run build
        env:
          CI: false
          GENERATE_SOURCEMAP: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: debate-ui/build/
          retention-days: 7

      - name: Upload test coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./debate-ui/coverage/lcov.info
          flags: frontend
          name: codecov-frontend

  # Contract Testing
  contract-tests:
    name: Contract Tests
    runs-on: ubuntu-latest
    needs: [java-services]
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Run Pact consumer tests
        run: |
          cd mcp-testing
          mvn test -Dtest=*PactTest -B

      - name: Publish Pact contracts
        if: github.ref == 'refs/heads/main'
        run: |
          cd mcp-testing
          mvn pact:publish -B
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

  # End-to-End Testing
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: [java-services, frontend]
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start services with Docker Compose
        run: |
          docker-compose -f docker-compose-testing.yml up -d
          sleep 30

      - name: Wait for services to be ready
        run: |
          ./scripts/testing/wait-for-services.sh

      - name: Set up Node.js for E2E tests
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: debate-ui/package-lock.json

      - name: Install E2E test dependencies
        working-directory: ./debate-ui
        run: npm ci

      - name: Run Playwright E2E tests
        working-directory: ./debate-ui
        run: npm run test:e2e
        env:
          CI: true

      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-test-results
          path: |
            debate-ui/test-results/
            debate-ui/playwright-report/
          retention-days: 7

      - name: Cleanup
        if: always()
        run: docker-compose -f docker-compose-testing.yml down -v

  # Security Testing
  security-tests:
    name: Security Tests
    runs-on: ubuntu-latest
    needs: [java-services]
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Start test services
        run: |
          docker-compose -f docker-compose-testing.yml up -d postgres redis
          sleep 10

      - name: Run security tests
        run: |
          cd mcp-testing
          mvn test -Dtest=SecurityTestSuite -B
        env:
          SPRING_PROFILES_ACTIVE: security-test

      - name: Run OWASP dependency check
        run: |
          mvn org.owasp:dependency-check-maven:check -B

      - name: Upload security test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-test-results
          path: |
            target/dependency-check-report.html
            mcp-testing/target/surefire-reports/
          retention-days: 7

  # Performance Testing
  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: [java-services]
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Start services for load testing
        run: |
          docker-compose -f docker-compose-performance.yml up -d
          sleep 60

      - name: Run Gatling load tests
        run: |
          cd load-tests
          mvn gatling:test -B

      - name: Upload performance test results
        uses: actions/upload-artifact@v4
        with:
          name: performance-test-results
          path: load-tests/target/gatling/
          retention-days: 30

      - name: Cleanup
        if: always()
        run: docker-compose -f docker-compose-performance.yml down -v

  # Build and Push Docker Images
  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [java-services, frontend, contract-tests]
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    
    strategy:
      matrix:
        service: [mcp-gateway, mcp-controller, mcp-organization, debate-ui]
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-

      - name: Download frontend build artifacts
        if: matrix.service == 'debate-ui'
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: debate-ui/build/

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  # Deploy to Staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build-images, e2e-tests, security-tests]
    if: github.ref == 'refs/heads/main'
    environment: staging
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.28.0'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG_STAGING }}" | base64 -d > $HOME/.kube/config

      - name: Deploy to staging
        run: |
          cd k8s/staging
          kubectl apply -k .
          kubectl rollout status deployment/mcp-gateway
          kubectl rollout status deployment/mcp-controller
          kubectl rollout status deployment/mcp-organization
          kubectl rollout status deployment/debate-ui

      - name: Run smoke tests
        run: |
          ./scripts/testing/smoke-tests.sh staging

      - name: Notify deployment status
        uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "Deployment to staging: ${{ job.status }}",
              "channel": "#deployments"
            }
        if: always()

  # Deploy to Production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [deploy-staging, performance-tests]
    if: github.event_name == 'release'
    environment: production
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.28.0'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG_PRODUCTION }}" | base64 -d > $HOME/.kube/config

      - name: Deploy to production
        run: |
          cd k8s/production
          kubectl apply -k .
          kubectl rollout status deployment/mcp-gateway
          kubectl rollout status deployment/mcp-controller
          kubectl rollout status deployment/mcp-organization
          kubectl rollout status deployment/debate-ui

      - name: Run production smoke tests
        run: |
          ./scripts/testing/smoke-tests.sh production

      - name: Update deployment tracking
        run: |
          curl -X POST "${{ secrets.DEPLOYMENT_WEBHOOK }}" \
            -H "Content-Type: application/json" \
            -d '{
              "version": "${{ github.event.release.tag_name }}",
              "environment": "production",
              "status": "success",
              "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            }'

      - name: Notify production deployment
        uses: slackapi/slack-github-action@v2
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "Production deployment completed for version ${{ github.event.release.tag_name }} - Status: ${{ job.status }}",
              "channel": "#production"
            }
        if: always()

  # Automated Workflow Failure Handler
  handle-cicd-failure:
    name: Handle CI/CD Pipeline Failure
    if: failure()
    needs: [security-scan, java-services, frontend, contract-tests, e2e-tests, security-tests, performance-tests, build-images, deploy-staging, deploy-production]
    uses: ./.github/workflows/workflow-failure-handler.yml
    with:
      workflow-name: "CI/CD Pipeline"
      # Dynamic severity based on what failed
      severity: ${{ (needs.deploy-production.result == 'failure') && 'critical' || (needs.deploy-staging.result == 'failure') && 'high' || (needs.security-tests.result == 'failure' || needs.security-scan.result == 'failure') && 'high' || (needs.e2e-tests.result == 'failure') && 'medium' || (github.ref == 'refs/heads/main') && 'high' || 'medium' }}
      # Dynamic assignees based on failure
      assignees: ${{ (needs.deploy-production.result == 'failure' || needs.deploy-staging.result == 'failure') && 'devops-team,platform-lead,oncall' || (needs.security-tests.result == 'failure' || needs.security-scan.result == 'failure') && 'security-team,team-lead' || (needs.java-services.result == 'failure') && 'backend-team' || (needs.frontend.result == 'failure') && 'frontend-team' || 'dev-team' }}
      # Comprehensive labels
      labels: "workflow-failure,ci-cd,branch-${{ github.ref_name }}"
      # Template selection
      template: ${{ (needs.deploy-production.result == 'failure' || needs.deploy-staging.result == 'failure') && 'deployment' || (needs.security-tests.result == 'failure' || needs.security-scan.result == 'failure') && 'security' || 'ci-cd' }}
      notify-slack: true
      notify-email: ${{ github.ref == 'refs/heads/main' || needs.deploy-production.result == 'failure' }}
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}