name: Dependency Updates

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:


permissions:
  actions: read
  contents: read
  pull-requests: write
jobs:
  update-maven-dependencies:
    name: Update Maven Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Update Maven dependencies
        run: |
          mvn versions:update-properties
          mvn versions:use-latest-releases

      - name: Run tests to verify updates
        run: mvn test -B

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update Maven dependencies'
          title: 'Update Maven dependencies'
          body: |
            This PR updates Maven dependencies to their latest versions.
            
            Changes:
            - Updated dependency versions
            - Verified with automated tests
            
            Please review the changes and merge if all tests pass.
          branch: dependencies/maven-updates
          delete-branch: true

  update-npm-dependencies:
    name: Update NPM Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./debate-ui
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: debate-ui/package-lock.json

      - name: Update NPM dependencies
        run: |
          npm update
          npm audit fix

      - name: Run tests to verify updates
        run: |
          npm run test
          npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update NPM dependencies'
          title: 'Update NPM dependencies'
          body: |
            This PR updates NPM dependencies to their latest versions.
            
            Changes:
            - Updated package.json and package-lock.json
            - Fixed security vulnerabilities
            - Verified with automated tests
            
            Please review the changes and merge if all tests pass.
          branch: dependencies/npm-updates
          delete-branch: true

  # Automated Workflow Failure Handler
  handle-dependency-update-failure:
    name: Handle Dependency Update Failure
    if: always() && (needs.update-maven-dependencies.result == 'failure' || needs.update-npm-dependencies.result == 'failure')
    needs: [update-maven-dependencies, update-npm-dependencies]
    uses: ./.github/workflows/workflow-failure-handler.yml
    with:
      workflow-name: "Dependency Updates"
      severity: "high"
      assignees: "security-team,devops-team,team-lead"
      labels: "workflow-failure,dependencies,security"
      template: "security"
      notify-slack: true
      notify-email: true
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}