name: Issue to Spec Conversion

on:
  issues:
    types: [assigned, labeled]

jobs:
  convert-to-spec:
    runs-on: ubuntu-latest
    # Only run if the issue is assigned to 'kiro-ai' or has the 'kiro-spec' label
    if: (github.event.issue.assignee.login == 'kiro-ai' || contains(github.event.issue.labels.*.name, 'kiro-spec'))
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Process issue and create spec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.repository }}
          KIRO_API_KEY: ${{ secrets.KIRO_API_KEY }}
        run: |
          python .github/scripts/issue_to_spec.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Create spec from issue #${{ github.event.issue.number }}"
          title: "Spec: ${{ github.event.issue.title }}"
          body: |
            This PR creates a spec from issue #${{ github.event.issue.number }}
            
            Original issue: ${{ github.event.issue.html_url }}
            
            The spec includes:
            - Requirements document
            - Design document
            - Tasks document
            
            Please review and merge if the spec looks good.
          branch: spec/issue-${{ github.event.issue.number }}
          base: main
          labels: spec, automated-pr