spring:
  application:
    name: mcp-context
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:context_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    show-sql: false
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  security:
    jwt:
      secret: ${JWT_SECRET:your-256-bit-secret-key-for-jwt-token-generation}
      expiration: 86400000  # 24 hours

server:
  port: ${SERVER_PORT:5007}
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: ${API_DOCS_PATH:/api-docs}
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    root: INFO
    com.zamaz.mcp.context: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:3001,http://localhost:5005,http://localhost:5006,http://localhost:5013}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  
  context:
    cache:
      ttl: ${CONTEXT_CACHE_TTL:3600}  # 1 hour in seconds
      max-size: ${CONTEXT_CACHE_MAX_SIZE:1000}
    window:
      default-size: ${CONTEXT_WINDOW_SIZE:4096}
      max-size: ${CONTEXT_MAX_WINDOW_SIZE:32768}
    version:
      retention-days: ${CONTEXT_VERSION_RETENTION:30}
    token:
      model: ${TOKEN_COUNT_MODEL:gpt-4}  # Model to use for token counting